version: '3'

services:
  status:
    environment:
      NODE_ENV: production
    volumes:
      - "/etc/direct-status:/etc/status"
      - "/var/lib/direct-status/db:/data/db"
      - "/var/lib/direct-status/storage.local:/data/storage.local"